title: AnthonyGonzales.dev
highlighter: rouge
markdown: kramdown
permalink: /blog/:title:output_ext
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
excerpt_separator: <!--break-->
sass:
    style: compressed
url: 'https://anthonygonzal.es'
repository: 'antgonzales/antgonzales.github.io'
exclude:
  - src/
  - public/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - Gemfile.cloudflare
  - _archived_posts/
